name: Upstream

on:
  workflow_dispatch:      # ejecución manual
  schedule:               # ejecución automática semanal
    - cron: "0 5 * * 0"   # dom 03:00 UTC → 05:00 hora peninsular

jobs:
  upstream:
    runs-on: ubuntu-latest
    # evita bucles si el commit lleva [ci‑skip]
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Update upstream
        run: ./scripts/updateUpstream.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
